"use client";

import { useLocale } from "next-intl";
import { Navigation } from "@/components/landing/navigation";
import { Footer } from "@/components/landing/footer";
import { Card } from "@/components/ui/card";
import { Shield } from "lucide-react";

export default function TermsPage() {
  const currentLocale = useLocale();
  const isTr = currentLocale === "tr";

  return (
    <div className="min-h-screen bg-zinc-50 flex flex-col font-sans antialiased text-zinc-900">
      <Navigation />

      <main className="flex-1 max-w-4xl w-full mx-auto px-4 sm:px-6 lg:px-8 py-32 space-y-16 animate-in fade-in duration-500">
        <div className="text-center space-y-4 max-w-2xl mx-auto">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-zinc-950/5 border border-black/5 text-zinc-800 text-xs font-black uppercase tracking-widest">
            <Shield className="w-3.5 h-3.5" />
            {isTr ? "SÖZLEŞME" : "AGREEMENT"}
          </div>
          <h1 className="text-4xl lg:text-6xl font-black tracking-tight text-zinc-950">
            {isTr ? "Kullanım Şartları" : "Terms of Service"}
          </h1>
        </div>

        <Card className="rounded-[32px] border border-black/5 bg-white shadow-xl p-8 lg:p-12 space-y-6 text-sm text-zinc-600 leading-relaxed font-medium">
          {isTr ? (
            <>
              <h3 className="text-xl font-black text-zinc-950">1. Lisans Kapsamı</h3>
              <p>J.Caesar otonom yapay zeka hizmeti, seçtiğiniz plana (Starter, Elite, Enterprise) göre belirlenen mesaj ve ajan limitleri dahilinde kullanım hakkı sunar. Lisans hakları başka hesaplara devredilemez.</p>
              
              <h3 className="text-xl font-black text-zinc-950">2. Sorumluluk Sınırları</h3>
              <p>Yapay zekanın sitenizde veya harici kanallarınızda (WhatsApp, Instagram vb.) vereceği yanıtlar tamamen bilgi tabanınızdaki verilerle eğitilir. Yapay zeka yanıtlarının doğruluğunu ve müşteri etkileşimlerini kontrol etmek kullanıcının sorumluluğundadır.</p>
            </>
          ) : (
            <>
              <h3 className="text-xl font-black text-zinc-950">1. Account Allocations</h3>
              <p>J.Caesar grants active subscribers a non-exclusive license to configure and deploy AI agents within the monthly limits (messages and agent numbers) specified in their selected plan tier.</p>
              
              <h3 className="text-xl font-black text-zinc-950">2. Service Liability</h3>
              <p>Conversation flows and automated actions are directly driven by your custom datasets. Subscribers are solely responsible for ensuring the accuracy and legal compliance of replies generated by their trained agents.</p>
            </>
          )}
        </Card>
      </main>

      <Footer />
    </div>
  );
}
